# Configurações gerais da aplicação
spring.application.name=mecanica-diesel
# Porta padrão do servidor
server.port=1080

# Configurações do banco de dados
# URL de conexão para o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mecanica-diesel
# Usuario e senha
spring.datasource.username=root
spring.datasource.password=
# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
